begin
  failed ||= 0
  puts 'trying ...'
  process!
rescue => exception # !> assigned but unused variable - exception
  failed += 1
  retry if failed < 5
end
# >> trying ...
# >> trying ...
# >> trying ...
# >> trying ...
# >> trying ...